<?php
/**
 * MineAdmin is committed to providing solutions for quickly building web applications
 * Please view the LICENSE file that was distributed with this source code,
 * For the full copyright and license information.
 * Thank you very much for using MineAdmin.
 *
 * @Author X.Mo<root@imoi.cn>
 * @Link   https://gitee.com/xmo/MineAdmin
 */

declare(strict_types=1);

namespace Mine\Command\Creater;

use Hyperf\Command\Annotation\Command;
use Mine\MineCommand;

/**
 * Class CreateModule
 * @Command
 * @package System\Command\Creater
 */
class CreateController extends MineCommand
{
    protected $name = 'mine:controller-gen';

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    public function handle()
    {
        // TODO: Implement handle() method.
    }
}