<?php

declare(strict_types=1);
/**
 * This file is part of MineAdmin.
 *
 * @link     https://www.mineadmin.com
 * @document https://doc.mineadmin.com
 * @contact  root@imoi.cn
 * @license  https://github.com/mineadmin/MineAdmin/blob/master/LICENSE
 */
use App\Model\Permission\Menu;
use Hyperf\Database\Seeders\Seeder;
use Hyperf\DbConnection\Db;

class MenuSeeder extends Seeder
{
    public const BASE_DATA = [
        'name' => '',
        'code' => '',
        'icon' => '',
        'route' => '',
        'component' => '',
        'redirect' => '',
        'is_hidden' => '1',
        'type' => 'B',
        'created_by' => 0,
        'updated_by' => 0,
        'remark' => '',
    ];

    /**
     * Run the database seeds.
     */
    public function run()
    {
        Menu::truncate();
        if (env('DB_DRIVER') === 'odbc-sql-server') {
            Db::unprepared('SET IDENTITY_INSERT [' . Menu::getModel()->getTable() . '] ON;');
        }
        // TODO 早上继续
        return;
        $data = $this->data();
        $this->create($data);
        if (env('DB_DRIVER') === 'odbc-sql-server') {
            Db::unprepared('SET IDENTITY_INSERT [' . Menu::getModel()->getTable() . '] OFF;');
        }
    }

    /**
     * Database seeds data.
     */
    public function data(): array
    {
        return [
            [
                'name' => '权限',
                'code' => 'permission',
                'icon' => 'ma-icon-permission',
                'route' => 'permission',
                'is_hidden' => '2',
                'type' => 'M',
                'children' => [
                    [
                        'name' => '用户管理',
                        'code' => 'permission:user',
                        'icon' => 'ma-icon-user',
                        'route' => 'user',
                        'component' => 'permission/user/index',
                        'is_hidden' => '2',
                        'type' => 'M',
                        'children' => [
                            [
                                'name' => '用户列表',
                                'code' => 'permission:user:index',
                            ],
                            [
                                'name' => '用户回收站列表',
                                'code' => 'permission:user:recycle',
                            ],
                            [
                                'name' => '用户保存',
                                'code' => 'permission:user:save',
                            ],
                            [
                                'name' => '用户更新',
                                'code' => 'permission:user:update',
                            ],
                            [
                                'name' => '用户删除',
                                'code' => 'permission:user:delete',
                            ],
                            [
                                'name' => '用户读取',
                                'code' => 'permission:user:read',
                            ],
                            [
                                'name' => '用户恢复',
                                'code' => 'permission:user:recovery',
                            ],
                            [
                                'name' => '用户真实删除',
                                'code' => 'permission:user:realDelete',
                            ],
                            [
                                'name' => '用户导入',
                                'code' => 'permission:user:import',
                            ],
                            [
                                'name' => '用户导出',
                                'code' => 'permission:user:export',
                            ],
                            [
                                'name' => '用户状态改变',
                                'code' => 'permission:user:changeStatus',
                            ],
                            [
                                'name' => '用户初始化密码',
                                'code' => 'permission:user:initUserPassword',
                            ],
                            [
                                'name' => '更新用户缓存',
                                'code' => 'permission:user:cache',
                            ],
                            [
                                'name' => '设置用户首页',
                                'code' => 'permission:user:homePage',
                            ],
                        ],
                    ],
                    [
                        'name' => '菜单管理',
                        'code' => 'permission:menu',
                        'icon' => 'icon-menu',
                        'route' => 'menu',
                        'component' => 'permission/menu/index',
                        'is_hidden' => '2',
                        'type' => 'M',
                        'children' => [
                            [
                                'name' => '菜单列表',
                                'code' => 'permission:menu:index',
                            ],
                            [
                                'name' => '菜单回收站',
                                'code' => 'permission:menu:recycle',
                            ],
                            [
                                'name' => '菜单保存',
                                'code' => 'permission:menu:save',
                            ],
                            [
                                'name' => '菜单更新',
                                'code' => 'permission:menu:update',
                            ],
                            [
                                'name' => '菜单删除',
                                'code' => 'permission:menu:delete',
                            ],
                            [
                                'name' => '菜单读取',
                                'code' => 'permission:menu:read',
                            ],
                            [
                                'name' => '菜单恢复',
                                'code' => 'permission:menu:recovery',
                            ],
                            [
                                'name' => '菜单真实删除',
                                'code' => 'permission:menu:realDelete',
                            ],
                            [
                                'name' => '菜单导入',
                                'code' => 'permission:menu:import',
                            ],
                            [
                                'name' => '菜单导出',
                                'code' => 'permission:menu:export',
                            ],
                        ],
                    ],
                    [
                        'name' => '部门管理',
                        'code' => 'permission:dept',
                        'icon' => 'ma-icon-dept',
                        'route' => 'dept',
                        'component' => 'permission/dept/index',
                        'is_hidden' => '2',
                        'type' => 'M',
                        'children' => [
                            [
                                'name' => '部门列表',
                                'code' => 'permission:dept:index',
                            ],
                            [
                                'name' => '部门回收站',
                                'code' => 'permission:dept:recycle',
                            ],
                            [
                                'name' => '部门保存',
                                'code' => 'permission:dept:save',
                            ],
                            [
                                'name' => '部门更新',
                                'code' => 'permission:dept:update',
                            ],
                            [
                                'name' => '部门删除',
                                'code' => 'permission:dept:delete',
                            ],
                            [
                                'name' => '部门读取',
                                'code' => 'permission:dept:read',
                            ],
                            [
                                'name' => '部门恢复',
                                'code' => 'permission:dept:recovery',
                            ],
                            [
                                'name' => '部门真实删除',
                                'code' => 'permission:dept:realDelete',
                            ],
                            [
                                'name' => '部门导入',
                                'code' => 'permission:dept:import',
                            ],
                            [
                                'name' => '部门导出',
                                'code' => 'permission:dept:export',
                            ],
                            [
                                'name' => '部门状态改变',
                                'code' => 'permission:dept:changeStatus',
                            ],
                        ],
                    ],
                    [
                        'name' => '角色管理',
                        'code' => 'permission:role',
                        'icon' => 'ma-icon-role',
                        'route' => 'role',
                        'component' => 'permission/role/index',
                        'is_hidden' => '2',
                        'type' => 'M',
                        'children' => [
                            [
                                'name' => '角色列表',
                                'code' => 'permission:role:index',
                            ],
                            [
                                'name' => '角色回收站',
                                'code' => 'permission:role:recycle',
                            ],
                            [
                                'name' => '角色保存',
                                'code' => 'permission:role:save',
                            ],
                            [
                                'name' => '角色更新',
                                'code' => 'permission:role:update',
                            ],
                            [
                                'name' => '角色删除',
                                'code' => 'permission:role:delete',
                            ],
                            [
                                'name' => '角色读取',
                                'code' => 'permission:role:read',
                            ],
                            [
                                'name' => '角色恢复',
                                'code' => 'permission:role:recovery',
                            ],
                            [
                                'name' => '角色真实删除',
                                'code' => 'permission:role:realDelete',
                            ],
                            [
                                'name' => '角色导入',
                                'code' => 'permission:role:import',
                            ],
                            [
                                'name' => '角色导出',
                                'code' => 'permission:role:export',
                            ],
                            [
                                'name' => '角色状态改变',
                                'code' => 'permission:role:changeStatus',
                            ],
                            [
                                'name' => '更新菜单权限',
                                'code' => 'permission:role:menuPermission',
                            ],
                            [
                                'name' => '更新数据权限',
                                'code' => 'permission:role:dataPermission',
                            ],
                        ],
                    ],
                    [
                        'name' => '岗位管理',
                        'code' => 'permission:post',
                        'icon' => 'ma-icon-post',
                        'route' => 'post',
                        'component' => 'permission/post/index',
                        'is_hidden' => '2',
                        'type' => 'M',
                        'children' => [
                            53 => [
                                'name' => '岗位列表',
                                'code' => 'permission:post:index',
                            ],
                            [
                                'name' => '岗位回收站',
                                'code' => 'permission:post:recycle',
                            ],
                            [
                                'name' => '岗位保存',
                                'code' => 'permission:post:save',
                            ],
                            [
                                'name' => '岗位更新',
                                'code' => 'permission:post:update',
                            ],
                            [
                                'name' => '岗位删除',
                                'code' => 'permission:post:delete',
                            ],
                            [
                                'name' => '岗位读取',
                                'code' => 'permission:post:read',
                            ],
                            [
                                'name' => '岗位恢复',
                                'code' => 'permission:post:recovery',
                            ],
                            [
                                'name' => '岗位真实删除',
                                'code' => 'permission:post:realDelete',
                            ],
                            [
                                'name' => '岗位导入',
                                'code' => 'permission:post:import',
                            ],
                            [
                                'name' => '岗位导出',
                                'code' => 'permission:post:export',
                            ],
                            [
                                'name' => '岗位状态改变',
                                'code' => 'system:post:changeStatus',
                            ],
                        ],
                    ],
                ],
            ],
            [
                'name' => '数据',
                'code' => 'dataCenter',
                'icon' => 'icon-storage',
                'route' => 'dataCenter',
                'is_hidden' => '2',
                'type' => 'M',
                'children' => [
                    [
                        'name' => '数据字典',
                        'code' => 'dataCenter:dict',
                        'icon' => 'ma-icon-dict',
                        'route' => 'dict',
                        'component' => 'dataCenter/dict/index',
                        'is_hidden' => '2',
                        'type' => 'M',
                        'children' => [
                            [
                                'name' => '数据字典列表',
                                'code' => 'dataCenter:dict:index',
                            ],
                            [
                                'name' => '数据字典回收站',
                                'code' => 'dataCenter:dict:recycle',
                            ],
                            [
                                'name' => '数据字典保存',
                                'code' => 'dataCenter:dict:save',
                            ],
                            [
                                'name' => '数据字典更新',
                                'code' => 'dataCenter:dict:update',
                            ],
                            [
                                'name' => '数据字典删除',
                                'code' => 'dataCenter:dict:delete',
                            ],
                            [
                                'name' => '数据字典读取',
                                'code' => 'dataCenter:dict:read',
                            ],
                            [
                                'name' => '数据字典恢复',
                                'code' => 'dataCenter:dict:recovery',
                            ],
                            [
                                'name' => '数据字典真实删除',
                                'code' => 'dataCenter:dict:realDelete',
                            ],
                            [
                                'name' => '数据字典导入',
                                'code' => 'dataCenter:dict:import',
                            ],
                            [
                                'name' => '数据字典导出',
                                'code' => 'dataCenter:dict:export',
                            ],
                        ],
                    ],
                    [
                        'name' => '附件管理',
                        'code' => 'dataCenter:attachment',
                        'icon' => 'ma-icon-attach',
                        'route' => 'attachment',
                        'component' => 'dataCenter/attachment/index',
                        'is_hidden' => '2',
                        'type' => 'M',
                        'children' => [
                            [
                                'name' => '附件列表',
                                'code' => 'dataCenter:attachment:index',
                            ],
                            [
                                'name' => '附件删除',
                                'code' => 'dataCenter:attachment:delete',
                            ],
                            [
                                'name' => '附件回收站',
                                'code' => 'dataCenter:attachment:recycle',
                            ],
                            [
                                'name' => '附件真实删除',
                                'code' => 'dataCenter:attachment:realDelete',
                            ],
                        ],
                    ],
                    [
                        'name' => '数据表维护',
                        'code' => 'dataCenter:dataMaintain',
                        'icon' => 'ma-icon-db',
                        'route' => 'dataMaintain',
                        'component' => 'dataCenter/dataMaintain/index',
                        'is_hidden' => '2',
                        'type' => 'M',
                        'children' => [
                            [
                                'name' => '数据表列表',
                                'code' => 'dataCenter:dataMaintain:index',
                            ],
                            [
                                'name' => '数据表详细',
                                'code' => 'dataCenter:dataMaintain:detailed',
                            ],
                            [
                                'name' => '数据表清理碎片',
                                'code' => 'dataCenter:dataMaintain:fragment',
                            ],
                            [
                                'name' => '数据表优化',
                                'code' => 'dataCenter:dataMaintain:optimize',
                            ],
                        ],
                    ],
                    [
                        'name' => '系统公告',
                        'code' => 'dataCenter:notice',
                        'icon' => 'icon-bulb',
                        'route' => 'notice',
                        'component' => 'dataCenter/notice/index',
                        'is_hidden' => '2',
                        'type' => 'M',
                        'children' => [
                            [
                                'name' => '系统公告列表',
                                'code' => 'dataCenter:notice:index',
                            ],
                            [
                                'name' => '系统公告回收站',
                                'code' => 'dataCenter:notice:recycle',
                            ],
                            [
                                'name' => '系统公告保存',
                                'code' => 'dataCenter:notice:save',
                            ],
                            [
                                'name' => '系统公告更新',
                                'code' => 'dataCenter:notice:update',
                            ],
                            [
                                'name' => '系统公告删除',
                                'code' => 'dataCenter:notice:delete',
                            ],
                            [
                                'name' => '系统公告读取',
                                'code' => 'dataCenter:notice:read',
                            ],
                            [
                                'name' => '系统公告恢复',
                                'code' => 'dataCenter:notice:recovery',
                            ],
                            [
                                'name' => '系统公告真实删除',
                                'code' => 'dataCenter:notice:realDelete',
                            ],
                            [
                                'name' => '系统公告导入',
                                'code' => 'dataCenter:notice:import',
                            ],
                            [
                                'name' => '系统公告导出',
                                'code' => 'dataCenter:notice:export',
                            ],
                        ],
                    ],
                ],
            ],
            [
                'name' => '监控',
                'code' => 'monitor',
                'icon' => 'icon-desktop',
                'route' => 'monitor',
                'is_hidden' => '2',
                'type' => 'M',
                'children' => [
                    86 => [
                        'id' => 3200,
                        'parent_id' => 3000,
                        'level' => '0,3000',
                        'name' => '服务监控',
                        'code' => 'system:monitor:server',
                        'icon' => 'icon-thunderbolt',
                        'route' => 'server',
                        'component' => 'system/monitor/server/index',
                        'is_hidden' => '2',
                        'type' => 'M',
                    ],
                ],
            ],

            87 => [
                'id' => 3300,
                'parent_id' => 3000,
                'level' => '0,3000',
                'name' => '日志监控',
                'code' => 'logs',
                'icon' => 'icon-book',
                'route' => 'logs',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '2',
                'type' => 'M',
                'status' => 1,
                'sort' => 95,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            88 => [
                'id' => 3400,
                'parent_id' => 3300,
                'level' => '0,3000,3200',
                'name' => '登录日志',
                'code' => 'system:loginLog',
                'icon' => 'icon-idcard',
                'route' => 'loginLog',
                'component' => 'system/logs/loginLog',
                'redirect' => '',
                'is_hidden' => '2',
                'type' => 'M',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            89 => [
                'id' => 3401,
                'parent_id' => 3400,
                'level' => '0,3000,3200,3300',
                'name' => '登录日志删除',
                'code' => 'system:loginLog:delete',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            90 => [
                'id' => 3500,
                'parent_id' => 3300,
                'level' => '0,3000,3200',
                'name' => '操作日志',
                'code' => 'system:operLog',
                'icon' => 'icon-robot',
                'route' => 'operLog',
                'component' => 'system/logs/operLog',
                'redirect' => '',
                'is_hidden' => '2',
                'type' => 'M',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            91 => [
                'id' => 3501,
                'parent_id' => 3500,
                'level' => '0,3000,3200,3400',
                'name' => '操作日志删除',
                'code' => 'system:operLog:delete',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            92 => [
                'id' => 3600,
                'parent_id' => 3000,
                'level' => '0,3000',
                'name' => '在线用户',
                'code' => 'system:onlineUser',
                'icon' => 'ma-icon-online',
                'route' => 'onlineUser',
                'component' => 'system/monitor/onlineUser/index',
                'redirect' => '',
                'is_hidden' => '2',
                'type' => 'M',
                'status' => 1,
                'sort' => 98,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            93 => [
                'id' => 3601,
                'parent_id' => 3500,
                'level' => '0,3000,3500',
                'name' => '在线用户列表',
                'code' => 'system:onlineUser:index',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            94 => [
                'id' => 3602,
                'parent_id' => 3500,
                'level' => '0,3000,3500',
                'name' => '强退用户',
                'code' => 'system:onlineUser:kick',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            95 => [
                'id' => 4000,
                'parent_id' => 0,
                'level' => '0',
                'name' => '工具',
                'code' => 'devTools',
                'icon' => 'ma-icon-tool',
                'route' => 'devTools',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '2',
                'type' => 'M',
                'status' => 1,
                'sort' => 95,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            96 => [
                'id' => 4100,
                'parent_id' => 4000,
                'level' => '0,4000',
                'name' => '模块管理',
                'code' => 'setting:module',
                'icon' => 'icon-folder',
                'route' => 'module',
                'component' => 'setting/module/index',
                'redirect' => '',
                'is_hidden' => '2',
                'type' => 'M',
                'status' => 1,
                'sort' => 99,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            97 => [
                'id' => 4101,
                'parent_id' => 4100,
                'level' => '0,4000,4100',
                'name' => '新增模块',
                'code' => 'setting:module:save',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            98 => [
                'id' => 4102,
                'parent_id' => 4100,
                'level' => '0,4000,4100',
                'name' => '模块删除',
                'code' => 'setting:module:delete',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            99 => [
                'id' => 4103,
                'parent_id' => 4100,
                'level' => '0,4000,4100',
                'name' => '模块列表',
                'code' => 'setting:module:index',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            100 => [
                'id' => 4200,
                'parent_id' => 4000,
                'level' => '0,4000',
                'name' => '代码生成器',
                'code' => 'setting:code',
                'icon' => 'ma-icon-code',
                'route' => 'code',
                'component' => 'setting/code/index',
                'redirect' => '',
                'is_hidden' => '2',
                'type' => 'M',
                'status' => 1,
                'sort' => 98,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            101 => [
                'id' => 4201,
                'parent_id' => 4200,
                'level' => '0,4000,4200',
                'name' => '预览代码',
                'code' => 'setting:code:preview',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            102 => [
                'id' => 4202,
                'parent_id' => 4200,
                'level' => '0,4000,4200',
                'name' => '装载数据表',
                'code' => 'setting:code:loadTable',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            103 => [
                'id' => 4203,
                'parent_id' => 4200,
                'level' => '0,4000,4200',
                'name' => '删除业务表',
                'code' => 'setting:code:delete',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            104 => [
                'id' => 4204,
                'parent_id' => 4200,
                'level' => '0,4000,4200',
                'name' => '同步业务表',
                'code' => 'setting:code:sync',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            105 => [
                'id' => 4205,
                'parent_id' => 4200,
                'level' => '0,4000,4200',
                'name' => '生成代码',
                'code' => 'setting:code:generate',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            115 => [
                'id' => 4500,
                'parent_id' => 0,
                'level' => '0',
                'name' => '系统设置',
                'code' => 'setting:config',
                'icon' => 'icon-settings',
                'route' => 'system',
                'component' => 'setting/config/index',
                'redirect' => '',
                'is_hidden' => '2',
                'type' => 'M',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            116 => [
                'id' => 4502,
                'parent_id' => 4500,
                'level' => '0,4500',
                'name' => '配置列表',
                'code' => 'setting:config:index',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            117 => [
                'id' => 4504,
                'parent_id' => 4500,
                'level' => '0,4500',
                'name' => '新增配置 ',
                'code' => 'setting:config:save',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            118 => [
                'id' => 4505,
                'parent_id' => 4500,
                'level' => '0,4500',
                'name' => '更新配置',
                'code' => 'setting:config:update',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            119 => [
                'id' => 4506,
                'parent_id' => 4500,
                'level' => '0,4500',
                'name' => '删除配置',
                'code' => 'setting:config:delete',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            120 => [
                'id' => 4507,
                'parent_id' => 4500,
                'level' => '0,4500',
                'name' => '清除配置缓存',
                'code' => 'setting:config:clearCache',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            171 => [
                'id' => 3700,
                'parent_id' => 3000,
                'level' => '0,3000',
                'name' => '缓存监控',
                'code' => 'system:cache',
                'icon' => 'icon-dice',
                'route' => 'cache',
                'component' => 'system/monitor/cache/index',
                'redirect' => '',
                'is_hidden' => '2',
                'type' => 'M',
                'status' => 1,
                'sort' => 98,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            172 => [
                'id' => 3701,
                'parent_id' => 3700,
                'level' => '0,3000,3700',
                'name' => '获取Redis信息',
                'code' => 'system:cache:monitor',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            173 => [
                'id' => 3702,
                'parent_id' => 3700,
                'level' => '0,3000,3700',
                'name' => '删除一个缓存',
                'code' => 'system:cache:delete',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            174 => [
                'id' => 3703,
                'parent_id' => 3700,
                'level' => '0,3000,3700',
                'name' => '清空所有缓存',
                'code' => 'system:cache:clear',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            177 => [
                'id' => 2112,
                'parent_id' => 2100,
                'level' => '0,2000,2100',
                'name' => '字典状态改变',
                'code' => 'system:dataDict:changeStatus',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            178 => [
                'id' => 3850,
                'parent_id' => 3300,
                'level' => '0,3000,3300',
                'name' => '队列日志',
                'code' => 'system:queueLog',
                'icon' => 'icon-layers',
                'route' => 'queueLog',
                'component' => 'system/logs/queueLog',
                'redirect' => '',
                'is_hidden' => '2',
                'type' => 'M',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            179 => [
                'id' => 3851,
                'parent_id' => 3850,
                'level' => '0,3000,3300,3850',
                'name' => '删除队列日志',
                'code' => 'system:queueLog:delete',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            180 => [
                'id' => 3852,
                'parent_id' => 3850,
                'level' => '0,3000,3300,3850',
                'name' => '更新队列状态',
                'code' => 'system:queueLog:updateStatus',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => '1',
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],

            194 => [
                'id' => 4600,
                'parent_id' => 4000,
                'level' => '0,4000',
                'name' => '系统接口',
                'code' => 'systemInterface',
                'icon' => 'icon-compass',
                'route' => 'systemInterface',
                'component' => 'setting/systemInterface/index',
                'redirect' => '',
                'is_hidden' => '2',
                'type' => 'M',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            195 => [
                'id' => 4700,
                'parent_id' => 4000,
                'level' => '0,4000',
                'name' => '数据源管理',
                'code' => 'setting:datasource',
                'icon' => 'icon-storage',
                'route' => 'setting/datasource',
                'component' => 'setting/datasource/index',
                'redirect' => '',
                'is_hidden' => '2',
                'type' => 'M',
                'status' => '1',
                'sort' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'deleted_at' => null,
                'remark' => '',
            ],
            196 => [
                'id' => 4701,
                'parent_id' => 4700,
                'level' => '0,4000,4700',
                'name' => '数据源管理列表',
                'code' => 'setting:datasource:index',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => 2,
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0, // 假设创建者ID为0
                'updated_by' => 0, // 假设更新者ID为0

                'deleted_at' => null,
                'remark' => '',
            ],
            197 => [
                'id' => 4702,
                'parent_id' => 4700,
                'level' => '0,4000,4700',
                'name' => '数据源管理保存',
                'code' => 'setting:datasource:save',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => 2,
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            198 => [
                'id' => 4703,
                'parent_id' => 4700,
                'level' => '0,4000,4700',
                'name' => '数据源管理更新',
                'code' => 'setting:datasource:update',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => 2,
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,
                'deleted_at' => null,
                'remark' => '',
            ],
            199 => [
                'id' => 4704,
                'parent_id' => 4700,
                'level' => '0,4000,4700',
                'name' => '数据源管理读取',
                'code' => 'setting:datasource:read',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => 2,
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            200 => [
                'id' => 4705,
                'parent_id' => 4700,
                'level' => '0,4000,4700',
                'name' => '数据源管理删除',
                'code' => 'setting:datasource:delete',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => 2,
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            201 => [
                'id' => 4706,
                'parent_id' => 4700,
                'level' => '0,4000,4700',
                'name' => '数据源管理导入',
                'code' => 'setting:datasource:import',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => 2,
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
            202 => [
                'id' => 4707,
                'parent_id' => 4700,
                'level' => '0,4000,4700',
                'name' => '数据源管理导出',
                'code' => 'setting:datasource:export',
                'icon' => '',
                'route' => '',
                'component' => '',
                'redirect' => '',
                'is_hidden' => 2,
                'type' => 'B',
                'status' => 1,
                'sort' => 0,
                'created_by' => 0,
                'updated_by' => 0,

                'deleted_at' => null,
                'remark' => '',
            ],
        ];
    }

    public function create($parent) {}
}
