name: MineAdmin

volumes:
  mine_redis_data:
  mine_mysql_data:

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - mine_redis_data:/data
    command: redis-server --appendonly yes
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - TZ=Asia/Shanghai

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mine_mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mineadmin
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      TZ: Asia/Shanghai
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p root" ]
      interval: 5s
      timeout: 5s
      retries: 10

  mineadmin:
    image: hyperf/hyperf:8.3-alpine-v3.20-swoole-slim-v5.1.5
    container_name: mineadmin
    volumes:
      - ./:/www
    working_dir: /www
    ports:
      - "9501:9501"
      - "9503:9503"
    environment:
      - TZ=Asia/Shanghai
      - APP_NAME=MineAdmin
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    command:
      - sh
      - -c
      - |
        ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
        tail -F /dev/null
