<?php

declare(strict_types=1);
/**
 * This file is part of MineAdmin.
 *
 * @link     https://www.mineadmin.com
 * @document https://doc.mineadmin.com
 * @contact  root@imoi.cn
 * @license  https://github.com/mineadmin/MineAdmin/blob/master/LICENSE
 */

namespace App\Service\Permission;

use App\Exception\BusinessException;
use App\Http\Common\ResultCode;
use App\Library\DataPermission\Attribute\DataScope;
use App\Library\DataPermission\ScopeType;
use App\Model\Permission\Role;
use App\Model\Permission\User;
use App\Repository\Permission\RoleRepository;
use App\Repository\Permission\UserRepository;
use App\Service\IService;
use Hyperf\Collection\Collection;
use Hyperf\DbConnection\Db;
use Psr\SimpleCache\CacheInterface;

/**
 * @extends IService<User>
 */
final class UserService extends IService
{
    public function __construct(
        protected readonly UserRepository $repository,
        protected readonly RoleRepository $roleRepository,
        protected readonly CacheInterface $cache
    ) {}

    public function getInfo(int $id): ?User
    {
        if ($this->cache->has((string) $id)) {
            return $this->cache->get((string) $id);
        }
        $user = $this->repository->findById((string) $id);
        $this->cache->set((string) $id, $user, 60);
        return $user;
    }

    public function resetPassword(?int $id): bool
    {
        if ($id === null) {
            return false;
        }
        $entity = $this->repository->findById($id);
        $entity->resetPassword();
        $entity->save();
        return true;
    }

    public function getUserRole(int $id): Collection
    {
        return $this->repository->findById($id)->roles()->get();
    }

    public function batchGrantRoleForUser(int $id, array $roleCodes): void
    {
        $this->repository->findById($id)
            ->roles()
            ->sync(
                $this->roleRepository->list([
                    'code' => $roleCodes,
                ])->map(static function (Role $role) {
                    return $role->id;
                })
            );
    }

    public function create(array $data): mixed
    {
        return Db::transaction(function () use ($data) {
            /** @var User $entity */
            $entity = parent::create($data);
            $this->handleWith($entity, $data);
            return $entity;
        });
    }

    public function updateById(mixed $id, array $data): mixed
    {
        return Db::transaction(function () use ($id, $data) {
            /** @var null|User $entity */
            $entity = $this->repository->findById($id);
            if (empty($entity)) {
                throw new BusinessException(ResultCode::NOT_FOUND);
            }
            $entity->fill($data)->save();
            $this->handleWith($entity, $data);
        });
    }

    #[DataScope(
        scopeType: ScopeType::CREATED_BY,
        onlyTables: ['user'],
        createdByColumn: 'id'
    )]
    public function page(array $params, int $page = 1, int $pageSize = 10): array
    {
        return parent::page($params, $page, $pageSize); // TODO: Change the autogenerated stub
    }

    protected function handleWith(User $entity, array $data): void
    {
        if (isset($data['department'])) {
            $entity->department()->sync($data['department']);
        }
        if (isset($data['position'])) {
            $entity->position()->sync($data['position']);
        }
        if (isset($data['policy'])) {
            $policy = $entity->policy()->first();
            if ($policy) {
                if (isset($data['policy']['id'])) {
                    $policy->fill($data['policy'])->save();
                } else {
                    $entity->policy()->delete();
                }
            } else {
                if (! empty($data['policy'])) {
                    $entity->policy()->create($data['policy']);
                }
            }
        }
    }
}
