<?php
declare(strict_types=1);
namespace Mine\Command;

use Hyperf\Command\Annotation\Command;
use Mine\MineCommand;

/**
 * Class MineAdmin
 * @Command
 * @package System\Command
 */
class MineAdmin extends MineCommand
{
    protected $name = 'mine';

    public function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    /**
     * Handle the current command.
     */
    public function handle()
    {
        $this->line($this->getInfo(), 'comment');


    }
}