/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MaAuth: typeof import('./../src/components/ma-auth/index.vue')['default']
    MaCitySelect: typeof import('./../src/components/ma-city-select/index.vue')['default']
    MaDialog: typeof import('./../src/components/ma-dialog/index.vue')['default']
    MaDictCheckbox: typeof import('./../src/components/ma-dict-picker/ma-dict-checkbox.vue')['default']
    MaDictRadio: typeof import('./../src/components/ma-dict-picker/ma-dict-radio.vue')['default']
    MaDictSelect: typeof import('./../src/components/ma-dict-picker/ma-dict-select.vue')['default']
    MaDrawer: typeof import('./../src/components/ma-drawer/index.vue')['default']
    MaIconPanel: typeof import('./../src/components/ma-icon-picker/ma-icon-panel.vue')['default']
    MaIconPicker: typeof import('./../src/components/ma-icon-picker/index.vue')['default']
    MaRemoteSelect: typeof import('./../src/components/ma-remote-select/index.vue')['default']
    MaResourcePicker: typeof import('./../src/components/ma-resource-picker/index.vue')['default']
    MaSvgIcon: typeof import('./../src/components/ma-svg-icon/index.vue')['default']
    MaTree: typeof import('./../src/components/ma-tree/index.vue')['default']
    MaUploadFile: typeof import('./../src/components/ma-upload-file/index.vue')['default']
    MaUploadImage: typeof import('./../src/components/ma-upload-image/index.vue')['default']
    MaVerifyCode: typeof import('./../src/components/ma-verify-code/index.vue')['default']
    Panel: typeof import('./../src/components/ma-resource-picker/panel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
