/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MaAuth: typeof import('./../src/components/ma-auth/index.vue')['default']
    MaIconPanel: typeof import('./../src/components/ma-icon-picker/ma-icon-panel.vue')['default']
    MaIconPicker: typeof import('./../src/components/ma-icon-picker/index.vue')['default']
    MaResourcePicker: typeof import('./../src/components/ma-resource-picker/index.vue')['default']
    MaSvgIcon: typeof import('./../src/components/ma-svg-icon/index.vue')['default']
    MaTree: typeof import('./../src/components/ma-tree/index.vue')['default']
    MaVerifyCode: typeof import('./../src/components/ma-verify-code/index.vue')['default']
    Panel: typeof import('./../src/components/ma-resource-picker/panel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
